all:

Crossover:
	javac Crossover.java
	java Crossover
	cat crossover.out
Mutation:
	javac Mutation.java
	java Mutation
	cat mutation.out
Start:
	javac Start.java
	java Start
	cat start.out
Trees:
	javac Trees.java
	java Trees
	cat trees.out
clean:
	rm -f *.class
