all:

Minimization:
	javac Minimization.java
	java Minimization
Discrete:
	javac Discrete.java
	java -ea Discrete
	cat discrete.out
Continuous:
	javac Continuous.java
	java Continuous
	cat continuous.out
clean:
	rm -f *.class
